kind: workflow
trigger:
  kind: OnConversationStart
  id: trigger_wf
  actions:
    - kind: InvokeAzureAgent
      id: workflow-design-description-agent
      agent:
        name: workflow-design-description-agent
      description: First agent in sequential workflow
      conversationId: =System.ConversationId
      input:
        messages: =System.LastMessage
      output:
        messages: Local.LatestMessage
        autoSend: true
    - kind: InvokeAzureAgent
      id: workflow-design-yaml-agent
      agent:
        name: workflow-design-yaml-agent
      conversationId: =System.ConversationId
      description: Second agent in sequential workflow
      input:
        messages: =Local.LatestMessage
      output:
        messages: Local.LatestMessage
        autoSend: true
    - kind: EndConversation
      id: action-1768206049242
id: ""
name: creator-wf-workflow
description: ""
